### ISSUE TITLE
ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by loretoparisi** [nomad/cupertino#106]
MacBook-Pro-di-Loreto:appledoc admin$ sudo gem install cupertino
Building native extensions.  This could take a while...
ERROR:  Error installing cupertino:
    ERROR: Failed to build gem native extension.

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
```

mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/include/ruby.h

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/nokogiri-1.5.11 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/nokogiri-1.5.11/ext/nokogiri/gem_make.out

**Comment by cezheng** [comment]
@gnustep How did you resolve that problem? I'm installing another Gem that uses unf_ext, and I'm having exactly the same problem as yours with Xcode 7.3.1

```
compiling unf.cc
In file included from unf.cc:1:
./unf/normalizer.hh:4:10: fatal error: 'vector' file not found
#include <vector>
         ^
1 error generated.
make: *** [unf.o] Error 1

make failed, exit code 2
```
