### ISSUE TITLE
app_ids:add does not seem to work

### ISSUE THREAD

**Issue by Saturn49** [nomad/cupertino#179]
I'm getting an error when I try to use app_ids:add Name=SomeName

421 =>  for https://developer.apple.com/services-account/XXXXXX/account/ios/identifiers/addAppId.action?content-type=application/x-www-form-urlencoded&accept=application/json&requestId=XXXXXXXXXXX-XXXX-XXXX-XXXX-XXXXXX&userLocale=en_US&teamId=XXXXXXXXX -- unhandled response. Use --trace to view backtrace

**Comment by robwithhair** [comment]
I am getting the same error

**Comment by toobulkeh** [comment]
This process changed on Apple's portal - https://github.com/nomad/cupertino/blob/master/lib/cupertino/provisioning_portal/agent.rb#L298

It's no longer bundleConfirm.action and bundleSubmit and bundleSave. Looks like there's an extra step that hits `https://developer.apple.com/services-account/QH65B2/account/ios/identifiers/addAppId.action`.

I'll submit a PR in a bit.

**Comment by RocketPop** [comment]
Thanks for looking into this. My webdev/Ruby is too weak to help :)

**Comment by toobulkeh** [comment]
So I've finally figured out the weird patterns that this gem has and was able to tracedown and stub out the proper steps. Unfortunately I don't see what's wrong with my code, so I'm not doing a PR for it. Anyone's willing to chime in...

Note that our fork has other resources in it.

**Comment by toobulkeh** [comment]
So I've actually encountered what I think is the core problem, which is the inclusion of CSRF headers in the final JSON ajax form submission. Not all of their forms have it (creating certificates don't) but I believe adding app_ids and creating provisioning profiles both do.

I'm investigating a way to overcome this now, as it's not designed to protect against XSS (no captchas) so I should be able to overcome it.

**Comment by toobulkeh** [comment]
See https://github.com/sparklemotion/mechanize/issues/408 for some more details and discussion.

**Comment by toobulkeh** [comment]
Good news, this is finally fixed. I was missing the CSRF technique that Apple implemented (not XSS, so I think we're still in the clear).

I'll submit a PR after I work out a cleaner pattern, return some proper ID codes (instead of just assuming it works) and automate the last few things that are interactive (team selection, ew.)

**Comment by toobulkeh** [comment]
Here's a link to a fix incase anyone needs it before next week (or if I spontaneously combust) - https://github.com/QueueSoftwareInc/cupertino/commit/8edb126f75217e798ae3f401e05463da607275fa

**Comment by RocketPop** [comment]
Hmmm. @toobulkeh did you spontaneously combust? :) I may try your fork if this is fixed over there

**Comment by toobulkeh** [comment]
Oops! Sorry about that @RocketPop -- I did a PR for our fork which works: https://github.com/nomad/cupertino/pull/185

You might also want to check out this suite of tools, I haven't personally tried it, but it looks promising:
http://fastlane.tools/
