### ISSUE TITLE
Suggest: add support for generating push notification certificate

### ISSUE THREAD

**Issue by palxex** [nomad/cupertino#182]
Then generate csr/upload to apple and download cer/convert to pem will able to be done all in CLI.

**Comment by KrauseFx** [comment]
You might want to check out [PEM](https://github.com/KrauseFx/PEM) to automatically generate a `PEM` file for you.
It's an open source CLI, quite similar to `cupertino`, with the one and only task to do what you described.

**Comment by mattt** [comment]
@palxex This is out of scope for this project. You may want to consider the tool mentioned by @KrauseFx.
