### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by tychop** [nomad/cupertino#183]
Refresh & download Enterprise provisioning profiles

**Comment by KrauseFx** [comment]
@tychop, I published a tool, which does exactly that: [sigh](https://github.com/krausefx/sigh)
Does this help you?

**Comment by tychop** [comment]
Yes I alread found that (and immediatly asked for a nee feature ;-) )
Sigh will help us out. Thnx

**Comment by KrauseFx** [comment]
Glad I could help :+1:
