### ISSUE TITLE
how to implement automation with multiple teams?

### ISSUE THREAD

**Issue by DimaVartanian** [nomad/cupertino#186]
Hey Mattt! I'm currently using Jenkins for continuous integration and am writing a pre-build script that will refresh all of the provisioning profiles on the Jenkins device before trying to build the app in case they were invalidated due to an added device or something. I found that otherwise, I have to log into the box manually and refresh the accounts tab in Xcode.

Cupertino looks like the perfect tool to easily download all of our profiles and put them in the right place. My issue is that we use 2 teams (a Production one and an Enterprise one) and my script gets prompted on which team to choose rather than just downloading all of the profiles from both teams.

Do you have a recommendation on how to get around this? At first I was checking to see if there was an extra argument I could pass in to select the team using the first command (```ios profiles:download:all```) to avoid a second prompt but that doesn't appear to be the case. For the time being I am using Tcl expect with some success but it's not an ideal solution.

For what it's worth, here is the script I wrote which downloads all of the profiles from my first team:
```
#!/usr/bin/expect

set timeout 20

spawn ios profiles:download:all

expect "Select a team:" { send "1\r" }

interact
```

Any thoughts on this? Perhaps this would be something useful as a feature addition if there isn't a good way to do it currently.

edit: I'm seeing a ```--team``` switch in the internal help documentation but am unable to use it successfully. For instance: ```--team 1``` doesn't seem to do anything.

**Comment by tdemaio** [comment]
This might be what you're looking for:
  ios profiles:download:all --team $TEAMID --type distribution

via a previous comment here and the global options: https://github.com/nomad/cupertino/blob/master/lib/cupertino/provisioning_portal/commands.rb

Also, you'll find that Apple's TeamID will differ depending on the user that is logging in and their role in the dev portal.

**Comment by DimaVartanian** [comment]
Oh! looks like I was not using the correct parameter for teamid, using the actual ID from the dev center (rather than the number or the full string) seems to work!
