### ISSUE TITLE
Output markdown tables

### ISSUE THREAD

**Issue by mrkd** [nomad/cupertino#189]
Would it be possible to add a format option for markdown tables?

It looks like you are currently using https://github.com/tj/terminal-table - but I didn't see any option for markdown formatted tables

Maybe this could be done by editing the ASCII table style ?

**Comment by mattt** [comment]
FWIW, Markdown does not officially support tables, although some forks add support. I'm happy with just providing ASCII and CSV support. ASCII is a suitable default for terminal output, and all other possible renderings can be derived from the CSV output.
