### ISSUE TITLE
agent role only?

### ISSUE THREAD

**Issue by ronkorving** [nomad/cupertino#197]
Hi,

I'm trying to use cupertino (awesome tool btw, seriously) to automate a few tasks. I'm getting the impression that the only user account I can use is the one set up as "agent" (see: https://developer.apple.com/programs/roles/). Is this true, and if so, can anything be done about it? Even as admin I cannot list provisioning profiles.

```
$ ios profiles:list
error: Cupertino::ProvisioningPortal::UnexpectedContentError. Use --trace to view backtrace
```

**Comment by sfransen** [comment]
This is because apple changed the site this weekend

 Look at my agent.rb file 

https://github.com/sfransen/cupertino/blob/master/lib/cupertino/provisioning_portal/agent.rb

There is a fix for this problem.

**Comment by ronkorving** [comment]
Oh, great timing of me to start using cupertino :)
So I assume this fix is gonna land in the nomad repo at some point?

**Comment by sfransen** [comment]
the 1.3.3 have the fix but note that the add device to provision profile is
not fixed right now people are working on the problem.
 yes bad timing.

 by the way I been using this tool for 3 years now it is great

**Comment by ronkorving** [comment]
It totally is :) I'll keep providing feedback as I use this (only started using it since yesterday).
