### ISSUE TITLE
Feature request: non-interactive mode

### ISSUE THREAD

**Issue by ronkorving** [nomad/cupertino#202]
When using Cupertino in CI (eg Jenkins), the worst thing that can happen is an input prompt, but unfortunately when things go wrong that is often what Cupertino seems to do. When I, for example, attempt to download a provisioning profile which is either status "invalid" or misspelled or of the wrong type (distribution vs. development), I am presented with a list of profiles and a question which one I want to download.

Don't get me wrong, that can be a great feature for users. But for automation it's really quite annoying and I would _much_ rather get a nice fat error.

What do you think about this?

**Comment by tehnoir** [comment]
I would also find this useful. I would rather get an error than have a script hang waiting for user input.

**Comment by sfransen** [comment]
if you look at my branch I had this for 1 year now

**Comment by ronkorving** [comment]
How about some PRs then? :)

**Comment by sfransen** [comment]
I had this feature for a long time in my branch
I have one function to add add devices to all provision profiles
And another command to down all but the ones that are managed by Xcode as I hate those provision profiles

**Comment by icecrystal23** [comment]
Ping on this @sfransen can you update and make a pull request to master? Or let me know how to run your branch instead of this one.  Is there a way to do that via gem install or would I have to checkout and compile the source?

**Comment by sfransen** [comment]
No Code to replace just download the zip file and replace the code in the
folder  here is the location where to put it.


/Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.4  what every you have
installed.


open Terminal and install spaceship and cupertino


#if not done already

sudo xcode-select --install

sudo gem install cupertino

sudo gem install spaceship




download this zip file

https://github.com/sfransen/cupertino/archive/master.zip

unzip the file


 in Terminal again

open /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.4



 replace the the files in this folder from the zip file

 The files you need to replace are the ones in the lib folder


if you need more help let me know.

I should push a new version out there as I made some more changes


I hope this helps.


 you should check out fastlane and spaceship


https://github.com/fastlane/spaceship

 and

https://github.com/KrauseFx/fastlane


Steven Fransen

**Comment by sfransen** [comment]
No Code to compile just download the zip file and replace the code in the
folder  here is the location where to put it.  (Here is the correct
sentence)


/Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.4  what every you have
installed.


open Terminal and install spaceship and cupertino


#if not done already

sudo xcode-select --install

sudo gem install cupertino

sudo gem install spaceship




download this zip file

https://github.com/sfransen/cupertino/archive/master.zip

unzip the file


 in Terminal again

open /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.4



 replace the the files in this folder from the zip file

 The files you need to replace are the ones in the lib folder


if you need more help let me know.

I should push a new version out there as I made some more changes


I hope this helps.


 you should check out fastlane and spaceship


https://github.com/fastlane/spaceship

 and

https://github.com/KrauseFx/fastlane
