### ISSUE TITLE
downloading of certs failing due to pageNumber parameter not being passed

### ISSUE THREAD

**Issue by akohli** [nomad/cupertino#203]
unable to list certificates due what appears to be a bad request - the json body returned is:

{"responseId"=>"bc0532a4-1f36-4220-bfde-e0a05d849e4e", "resultCode"=>35, "resultString"=>"There were errors in the data supplied. Please correct and re-submit.", "userString"=>"An invalid value &#x27;0&#x27; was provided for the parameter &#x27;pageNumber&#x27;.\nAn invalid value &#x27;0&#x27; was provided for the parameter &#x27;pageSize&#x27;.", "creationTimestamp"=>"2015-04-16T13:54:42Z", "protocolVersion"=>"QH65B2", "requestId"=>"", "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com:443//services-account/QH65B2/account/ios/certificate/listCertRequests.action?content-type=text/x-url-arguments&accept=application/json&requestId=3bdbb0dd-0051-4ceb-b8f4-fb436d5fbe11&userLocale=en_US&teamId=N35AZHX79U&types=5QPB9NHCEI,BKLRAVXMGM&status=4&certificateStatus=0", "httpCode"=>200, "errorMessagesForXcode"=>nil, "suppressed"=>[], "validationMessages"=>[{"validationKey"=>"pageNumber", "validationUserMessage"=>"An invalid value &#x27;0&#x27; was provided for the parameter &#x27;pageNumber&#x27;."},

to the request:

I, [2015-04-16T14:54:42.489892 #5453]  INFO -- : Net::HTTP::Post: /services-account/QH65B2/account/ios/certificate/listCertRequests.action?content-type=text/x-url-arguments&accept=application/json&requestId=3bdbb0dd-0051-4ceb-b8f4-fb436d5fbe11&userLocale=en_US&teamId=<REDACTED>&types=5QPB9NHCEI,BKLRAVXMGM&status=4&certificateStatus=0

this is happening from agent.rb, ~line 90:

certificate_data_url += certificate_request_types + certificate_statuses

```
    post(certificate_data_url)
    certificate_data = page.content

    parsed_certificate_data = JSON.parse(certificate_data)
```

I am continuing debugging to see what the issue is, as it appears to be happening for profiles too.

**Comment by KrauseFx** [comment]
Are you using the latest version of `cupertino`?
