### ISSUE TITLE
((BUG?)) error:undefined method `each' for nil:NilClass. 

### ISSUE THREAD

**Issue by maksim2042** [nomad/cupertino#204]
gella:~ master$ ios login
Username:
<<<<hidden>>>>
Password:
*********
Account credentials saved

gella:~ master$ ios app_ids
error: undefined method `each' for nil:NilClass. Use --trace to view backtrace

gella:~ master$ ios app_ids --trace
/Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.1/lib/cupertino/provisioning_portal/agent.rb:345:in `list_app_ids': undefined method `each' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.1/lib/cupertino/provisioning_portal/commands/app_ids.rb:12:in `block (3 levels) in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.1/lib/cupertino/provisioning_portal/helpers.rb:58:in `try'
	from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.1/lib/cupertino/provisioning_portal/commands/app_ids.rb:12:in `block (2 levels) in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/runner.rb:426:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/import.rb:8:in `block in <top (required)>'
gella:~ master$

**Comment by sfransen** [comment]
Are you using that latest version this is working with the latest version

**Comment by maksim2042** [comment]
This was installed from gem

—

**Comment by sfransen** [comment]
It works for me

**Comment by sfransen** [comment]
Look at the agent file

**Comment by maksim2042** [comment]
Where is the agent file and what should I be looking for?

—

**Comment by mattt** [comment]
> `/Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.1`

@maksim2042 You're using an outdated version of Cupertino. Please update to the latest (1.3.3)
