### ISSUE TITLE
Unhandled exception while adding an app ID

### ISSUE THREAD

**Issue by maksim2042** [nomad/cupertino#205]
gella:cupertino master$ ios app_ids:add "Testing IDs"=HLXDAWPYG6.io.ocn.submittest --trace
/Library/Ruby/Gems/2.0.0/gems/mechanize-2.5.1/lib/mechanize/http/agent.rb:304:in `fetch': 421 =>  for https://developer.apple.com/services-account/QH65B2/account/ios/identifiers/addAppId.action?content-type=text/x-url-arguments&accept=application/json&requestId=6cb06fa8-5eac-4b40-9e9e-eb763df20211&userLocale=en_US&teamId=HLXDAWPYG6 -- unhandled response (Mechanize::ResponseCodeError)
    from /Library/Ruby/Gems/2.0.0/gems/mechanize-2.5.1/lib/mechanize.rb:1229:in`post_form'
    from /Library/Ruby/Gems/2.0.0/gems/mechanize-2.5.1/lib/mechanize.rb:515:in `submit'
    from /Library/Ruby/Gems/2.0.0/gems/mechanize-2.5.1/lib/mechanize/form.rb:178:in`submit'
    from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.3/lib/cupertino/provisioning_portal/agent.rb:330:in `add_app_id'
    from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.3/lib/cupertino/provisioning_portal/commands/app_ids.rb:63:in`block (3 levels) in <top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.3/lib/cupertino/provisioning_portal/commands/app_ids.rb:57:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.3/lib/cupertino/provisioning_portal/commands/app_ids.rb:57:in`block (2 levels) in <top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/command.rb:178:in`call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/command.rb:153:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/runner.rb:428:in`run_active_command'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/runner.rb:68:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/delegates.rb:15:in`run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/import.rb:8:in `block in <top (required)>'

**Comment by keanyc** [comment]
Anyone can help on this?

**Comment by gboruk** [comment]
+1 seeing the same error
