### ISSUE TITLE
Display Item number limit?

### ISSUE THREAD

**Issue by gianksp** [nomad/cupertino#206]
Displaying App Ids and provisioning profiles only return and evaluate the first 50 items. If you have more the rest are not taking into consideration even if trying to access a specific item.

**Comment by sfransen** [comment]
just change the number 50 to 500 and it will work fine.

Here the changes to make them work right
Note I was not able to change  bundle_data_url to 5000 it failed
        bundle_data_url += "&pageSize=50&pageNumber=1&sort=name=asc"
changed to
        bundle_data_url += "&pageSize=500&pageNumber=1&sort=name=asc"

      certificate_data_url += "&pageSize=50&pageNumber=1&sort=name=asc"
changed to
      certificate_data_url += "&pageSize=5000&pageNumber=1&sort=name=asc"

        device_data_url += "&pageSize=50&pageNumber=1&sort=name=asc"
changed to
        device_data_url += "&pageSize=5000&pageNumber=1&sort=name=asc"

        profile_data_url += "&pageSize=50&pageNumber=1&sort=name=asc"
changed to
        profile_data_url += "&pageSize=5000&pageNumber=1&sort=name=asc"

**Comment by gianksp** [comment]
Thank you, what I was looking for. Really appreciate it.

**Comment by sfransen** [comment]
No problem

**Comment by mattt** [comment]
Fixed by #216.
