### ISSUE TITLE
can't satisfy 'highline (>= 1.7.1)', already activated 'highline-1.6.21' (Gem::LoadError)

### ISSUE THREAD

**Issue by brianseeders** [nomad/cupertino#208]
After updating to the latest version of Cupertino, I get this on multiple machines:

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1206:in `block in activate_dependencies': can't satisfy 'highline (>= 1.7.1)', already activated 'highline-1.6.21' (Gem::LoadError)

Running on OSX Yosemite.

Any advice?

**Comment by KrauseFx** [comment]
Please update using `sudo gem update`. Sorry about the troubles.

**Comment by dankimio** [comment]
Should be fixed in the latest version.
