### ISSUE TITLE
Re-Authenticating

### ISSUE THREAD

**Issue by AndyIbanez** [nomad/cupertino#210]
I recently changed my iTunes Connect password and I'm trying to "re-authenticate" with Cupertino but I can't.

You are already authenticated
Username:
[redacted]
Password:
*
security: SecKeychainAddInternetPassword <NULL>: The specified item already exists in the keychain.
Error saving credentials

I have tried looking for the keychain item, but I have no idea what it is called so I can't find it. I am no Ruby programmer but I tried looking at the source and I couldn't deduce what the keychain item would be either.

We need a an easy way to reauthenticate.

**Comment by mattt** [comment]
> We need a an easy way to reauthenticate.

```
$ ios logout
$ ios login
```
