### ISSUE TITLE
undefined method `name' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by houweifeng** [nomad/cupertino#213]
/usr/lib/ruby/gems/2.0.0/gems/cupertino-1.3.3/lib/cupertino/provisioning_portal/commands/profiles.rb:144:in `block (5 levels) in <top (required)>': undefined method `name' for nil:NilClass (NoMethodError)
        from /usr/lib/ruby/gems/2.0.0/gems/cupertino-1.3.3/lib/cupertino/provisioning_portal/commands/profiles.rb:144:in `each'
        from /usr/lib/ruby/gems/2.0.0/gems/cupertino-1.3.3/lib/cupertino/provisioning_portal/commands/profiles.rb:144:in `detect'
        from /usr/lib/ruby/gems/2.0.0/gems/cupertino-1.3.3/lib/cupertino/provisioning_portal/commands/profiles.rb:144:in `block (4 levels) in <top (required)>'
        from /usr/lib/ruby/gems/2.0.0/gems/cupertino-1.3.3/lib/cupertino/provisioning_portal/commands/profiles.rb:141:in `each'
        from /usr/lib/ruby/gems/2.0.0/gems/cupertino-1.3.3/lib/cupertino/provisioning_portal/commands/profiles.rb:141:in `each_with_index'
        from /usr/lib/ruby/gems/2.0.0/gems/cupertino-1.3.3/lib/cupertino/provisioning_portal/commands/profiles.rb:141:in `block (3 levels) in <top (required)>'
        from /usr/lib/ruby/gems/2.0.0/gems/cupertino-1.3.3/lib/cupertino/provisioning_portal/agent.rb:259:in `manage_devices_for_profile'
        from /usr/lib/ruby/gems/2.0.0/gems/cupertino-1.3.3/lib/cupertino/provisioning_portal/commands/profiles.rb:140:in `block (2 levels) in <top (required)>'
        from /usr/lib/ruby/gems/2.0.0/gems/commander-4.3.2/lib/commander/command.rb:178:in `call'
        from /usr/lib/ruby/gems/2.0.0/gems/commander-4.3.2/lib/commander/command.rb:178:in `call'
        from /usr/lib/ruby/gems/2.0.0/gems/commander-4.3.2/lib/commander/command.rb:153:in `run'
        from /usr/lib/ruby/gems/2.0.0/gems/commander-4.3.2/lib/commander/runner.rb:426:in `run_active_command'
        from /usr/lib/ruby/gems/2.0.0/gems/commander-4.3.2/lib/commander/runner.rb:68:in `run!'
        from /usr/lib/ruby/gems/2.0.0/gems/commander-4.3.2/lib/commander/delegates.rb:15:in `run!'
        from /usr/lib/ruby/gems/2.0.0/gems/commander-4.3.2/lib/commander/import.rb:8:in `block in <top (required)>'

**Comment by sfransen** [comment]
You need to raise page limit

**Comment by houweifeng** [comment]
@sfransen thank you for this tip. I'll try it.

**Comment by mattt** [comment]
Fixed by #216.
