### ISSUE TITLE
Too many connection resets error

### ISSUE THREAD

**Issue by Diarrhio** [nomad/cupertino#215]
Today, out of the blue, after running perfectly on our CI servers for months, we're getting errors when calling ios profiles:download:all. The specific error is:

```error: too many connection resets (due to Connection reset by peer - Errno::ECONNRESET) after 0 requests on 70208379697300, last used 1431565263.6017852 seconds ago. Use --trace to view backtrace```

It's happening on all our CI machines, including our developer machines. Anyone else having this issue?

**Comment by tommeier** [comment]
:+1:can confirm also seeing this, and locally, even on a normal 'ios profiles' call.

```
ios profiles --trace
/opt/boxen/rbenv/versions/2.2.0/lib/ruby/2.2.0/net/protocol.rb:153:in `read_nonblock': too many connection resets (due to Connection reset by peer - Errno::ECONNRESET) after 0 requests on 70104852634460, last used 1431566109.6377442 seconds ago (Net::HTTP::Persistent::Error)
```

**Comment by sfransen** [comment]
I would add an delay between each one

**Comment by tommeier** [comment]
Its dying on an individual call too : `https://developer.apple.com/account/ios/profile/profileList.action?type=limited` on the get request of `cupertino/provisioning_portal/agent.rb:185:in `list_profiles'`

**Comment by sfransen** [comment]
You have latest version of Cupertino right it was working for me just few hours ago

**Comment by tommeier** [comment]
Yup `cupertino (1.3.3)`

**Comment by sfransen** [comment]
You have a lot of provision profiles?

**Comment by sfransen** [comment]
II just download all 500 of mine provision profile with no error

 check out my code

https://github.com/sfransen/cupertino

**Comment by sfransen** [comment]
this error is the pagenum is not high enough for the for loop

**Comment by tommeier** [comment]
Interesting, yeah I only have 10 provisioning profiles for this account loading. Following the requests:

```
Requesting: https://developer.apple.com/account/ios/profile/profileList.action?type=limited
0
{}
get
#<Net::HTTPFound:0x007fa39c3cc278>
REDIRECTED TO: https://idmsa.apple.com/IDMSWebAuth/login?&appIdKey=redacted&path=%2F%2Faccount%2Fios%2Fprofile%2FprofileList.action%3Ftype%3Dlimited
Requesting: https://idmsa.apple.com/IDMSWebAuth/login?&appIdKey=redacted&path=%2F%2Faccount%2Fios%2Fprofile%2FprofileList.action%3Ftype%3Dlimited
Requesting: https://idmsa.apple.com/IDMSWebAuth/authenticate;jsessionid=redacted
0
{"Content-Type"=>"application/x-www-form-urlencoded", "Content-Length"=>"261"}
post
#<Net::HTTPFound:0x007fa39d81e2a8>
REDIRECTED TO: https://developer.apple.com/account/ios/profile/profileList.action?type=limited
Requesting: https://developer.apple.com/account/ios/profile/profileList.action?type=limited
1
{}
get
#<Net::HTTPFound:0x007fa39d691a98>
REDIRECTED TO: http://developer.apple.com:443/account/selectTeam.action
Requesting: http://developer.apple.com:443/account/selectTeam.action
/opt/boxen/rbenv/versions/2.2.0/lib/ruby/2.2.0/net/protocol.rb:153:in `read_nonblock': too many connection resets (due to Connection reset by peer - Errno::ECONNRESET) after 0 requests on 70170329774520, last used 1431573580.995855 seconds ago (Net::HTTP::Persistent::Error)
```

**Comment by sfransen** [comment]
Very strange I tested on two different account one large and one normal
Is this a enterprise or normal account

I not tested on enterprise account but I can you need me too

**Comment by tommeier** [comment]
Just a normal account, where is the best spot to debug what is happening? Anything I can expand on? (sorry the underlying code is unfamiliar to me)

**Comment by sfransen** [comment]
Have you tried rebooting you machine

I seen this once

I going to bed been an long day
I will get you more info tomorrow unless someone else helps you in the meantime

**Comment by tommeier** [comment]
Thanks @sfransen! appreciate the help :) I'll keep digging, its not urgent yet for us, sleep well!

**Comment by tommeier** [comment]
Ok, i went back to dig into it a bit more, and low and behold it all works now. I didn't restart or anything, its just suddenly started going through fine both locally and on the CI server. Sorry I wasn't able to capture any more useful into why it was occuring, but I would guess its external to cupertino (would be awesome to capture the cause for an error message next time).

@Diarrhio is yours working now? One thing I *did* do today was remove a team member and regenerate provisioning profiles. Perhaps there is a correlation with that for my instance, or if an apple server for provisioning profiles was simply playing up.

**Comment by tommeier** [comment]
For more info, with no changes, this is the output of the same debugging hacks i'd added earlier:

```
$ ios profiles
Requesting: https://developer.apple.com/account/ios/profile/profileList.action?type=limited
0
{}
get
#<Net::HTTPFound:0x007fb1bf8beb10>
REDIRECTED TO: https://idmsa.apple.com/IDMSWebAuth/login?&appIdKey=redacted&path=%2F%2Faccount%2Fios%2Fprofile%2FprofileList.action%3Ftype%3Dlimited
Requesting: https://idmsa.apple.com/IDMSWebAuth/login?&appIdKey=redacted&path=%2F%2Faccount%2Fios%2Fprofile%2FprofileList.action%3Ftype%3Dlimited
Requesting: https://idmsa.apple.com/IDMSWebAuth/authenticate;jsessionid=redacted
0
{"Content-Type"=>"application/x-www-form-urlencoded", "Content-Length"=>"261"}
post
#<Net::HTTPFound:0x007fb1bbb8d700>
REDIRECTED TO: https://developer.apple.com/account/ios/profile/profileList.action?type=limited
Requesting: https://developer.apple.com/account/ios/profile/profileList.action?type=limited
1
{}
get
#<Net::HTTPFound:0x007fb1bb60bd18>
REDIRECTED TO: https://developer.apple.com/account/selectTeam.action
Requesting: https://developer.apple.com/account/selectTeam.action
Requesting: https://developer.apple.com/account/ios/profile/profileList.action?type=limited
0
{}
get
#<Net::HTTPFound:0x007fb1bbb97908>
REDIRECTED TO: https://developer.apple.com/account/selectTeam.action
Requesting: https://developer.apple.com/account/selectTeam.action
Select a team:
```

**Comment by tommeier** [comment]
ah interesting, note @sfransen it was redirecting while failing too `http://developer.apple.com:443/account/selectTeam.action`, but now it is succeeding the redirection is to  `https://developer.apple.com/account/selectTeam.action`. My guess would be a DNS update was faulty somewhere along the lines? (i'm in Australia), could also be cause as to why some and not all people saw it.

**Comment by Diarrhio** [comment]
Sorry I wasn't able to comment after my OP, left work for the day. It appears that whatever issue causing this is now resolved as things are back to normal. Sounds like it could have been a DNS issue as @tommeier pointed out.

**Comment by mattt** [comment]
Glad to hear things are working again now.

**Comment by kentpickard** [comment]
I am also getting this sporadically.  It seems like it happens once every 10 builds or so.  Here's the error from the TeamCity runner that is executing our rake script on the mac build server:

[Execute download_and_install_prov_profiles] ﻿error: too many connection resets (due to Net::ReadTimeout - Net::ReadTimeout) after 0 requests on 70174632801700, last used 1432734000.691846 seconds ago. Use --trace to view backtrace

I'll try adding --trace to see if I can get any useful info.

**Comment by quentinfasquel** [comment]
Getting the same issue, all the time now. And at some point I had an Apple html source that said "We'll be back soon", could it just be a server issue at Apple?

**Comment by KrauseFx** [comment]
The developer Portal just is **really** slow today.

**Comment by kentpickard** [comment]
Thanks @KrauseFx   you are right and it is indeed working again.  For future reference for anyone coming across this thread (as others have said), check developer.apple.com and make sure the site is responsive and that you can log in.  It may also be possible that a new EULA needs to be agreed to before provisioning profiles can be downloaded.
