### ISSUE TITLE
Adding of devices doesn't work

### ISSUE THREAD

**Issue by varuzhnikov** [nomad/cupertino#217]
When trying to add device or many devices via cupertino
error: 404 => Net::HTTPNotFound for https://developer.apple.com/account/ios/device/deviceImportUpload.action -- unhandled response. Use --trace to view backtrace

**Comment by KrauseFx** [comment]
Why did you close the issue? Was it just a temporary issue?

**Comment by varuzhnikov** [comment]
It was from Apple side. You can read on dev forums about this issue https://devforums.apple.com/message/1141198#1141198
