### ISSUE TITLE
iOS devices: add get error

### ISSUE THREAD

**Issue by sfransen** [nomad/cupertino#220]
```
/Library/Ruby/Gems/2.0.0/gems/mechanize-2.5.1/lib/mechanize/http/agent.rb:304:in `fetch': 415 => Net::HTTPUnsupportedMediaType for https://developer.apple.com/services-account/QH65B2/account/ios/device/addDevices.action?struts.token.name=clientToken&clientToken=6HC0POFGN7BZLYHS36QZ3BTNL9RN5R5U&deviceNames=foo&deviceNumbers=b0971d7697edf77cb8a03d131ad326b63c86d986 -- unhandled response (Mechanize::ResponseCodeError)
    from /Library/Ruby/Gems/2.0.0/gems/mechanize-2.5.1/lib/mechanize.rb:407:in`get'
    from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/agent.rb:45:in `block in get'
    from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/agent.rb:44:in`times'
    from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/agent.rb:44:in `get'
    from /Library/Ruby/Gems/2.0.0/gems/mechanize-2.5.1/lib/mechanize.rb:517:in`submit'
    from /Library/Ruby/Gems/2.0.0/gems/mechanize-2.5.1/lib/mechanize/form.rb:178:in `submit'
    from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/agent.rb:164:in`add_devices'
    from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/commands/devices.rb:79:in `block (2 levels) in <top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in`call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in`run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in`run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/import.rb:8:in`block in <top (required)>'
```

**Comment by miraculixx** [comment]
+1 same issue here. used to work like a breeze, not so much now.

The root cause is this:

```
curl "https://developer.apple.com/services-account/XXXX/account/ios/device/addDevices.action?struts.token.name=clientToken&clientToken=XXXXX&deviceNames=XXXX&deviceNumbers=XXX" --head
HTTP/1.1 401 Unauthorized
Server: nginx
Date: Tue, 09 Jun 2015 10:11:50 GMT
Content-Type: text/html
Content-Length: 188
Connection: keep-alive
```

Note this happens after correctly logging in:

```
$ ios login
Username:
Password:

Account credentials saved
```

**Comment by Pipen** [comment]
i'm guessing this is caused by the new developer pages

**Comment by mattnunes** [comment]
I had this issue as well. It has to do with Apple's new Developer program - you need to log in to the developer portal and accept the new Developer agreement. Until that happens, you'll keep getting `401` errors.

**Comment by sfransen** [comment]
I did that I can do everything but add device to license

**Comment by sfransen** [comment]
I tried several developer accounts and users same problem.

**Comment by sfransen** [comment]
I now get a error 415 

devices:list
devices:add
devices:add each
devices:add add_devices
add_devices
get
3 times
3 times
begin
each
add_devices else if form
get
3 times
error: 415 => Net::HTTPUnsupportedMediaType for https://developer.apple.com/services-account/xxxxxxx/account/ios/device/addDevices.action?struts.token.name=clientToken&clientToken=DDDDDDDDDDDD&deviceNames=xxxxxxx&deviceNumbers=xxxxxxxxxxxxxxxxxx -- unhandled response. Use --trace to view backtrace

**Comment by jeffbonnes** [comment]
We don't use Cupertino, but had the same issues at installrapp.com after Apple's changes on Tuesday.  We needed to add a csrf and csrf_ts header when registering devices just like issue #165.  We also changed our workflow to get the new deviceClasses parameter during the 'validation' process with Apple since Apple is separating iPads, iPhone, and iPod touches.

Note: Our unit tests didn't catch these errors as only real UDIDs seem to need the changes. The fake ones were were generating for our tests would register fine.  Only real UDIDs didn't work.

I hope that helps you find a solution!

**Comment by sfransen** [comment]
Thanks I will look tomorrow in bed already

I will take a peak at your app too

**Comment by knja** [comment]
please login on developer.apple.com with all your accounts and accept(twice!) new developer agreement.

**Comment by sfransen** [comment]
I have done this

**Comment by sfransen** [comment]
OK I was able to solve my problem using the new tool spaceship and I replace the device:add with the code to use spaceship. I will try and figure how to make it work here. But I just change to use  the code in there to fix my problem. check out  https://spaceship.airforce

**Comment by cybertk** [comment]
Same problem here after `ios logout; ios login` and accept all agreements.

```
$ ios devices:add xx=...
error: 415 => Net::HTTPUnsupportedMediaType for https://developer.apple.com/services-account/xx/account/ios/device/addDevices.action?struts.token.name=clientToken&clientToken=xx&deviceNames=xx&deviceNumbers=xx -- unhandled response. Use --trace to view backtrace
```

**Comment by sfransen** [comment]
I am using spaceship for this adding devices to licenses

**Comment by cybertk** [comment]
@sfransen thanks, I tried **spaceship**, it works like a charm.

**Comment by tehnoir** [comment]
Still no specific fix for cupertino?

**Comment by sfransen** [comment]
I can add the simple fix from spaceship that is what I am using for this fix

**Comment by tehnoir** [comment]
That would be helpful if it's not too much trouble.

**Comment by KrauseFx** [comment]
Here's the code you'd need in `spaceship` to register a new device:

```ruby
require 'spaceship`
Spaceship.login("user", "password")
Spaceship.device.create!(name: "iPhone 6", udid: "5814abb3...")
```

If you're using `fastlane` already, you can just skip the `password` value, or you can provide the password using the `DELIVER_PASSWORD` environment variable.

**Comment by KrauseFx** [comment]
Okay, here's a script to use:

```ruby
#!/usr/bin/env ruby
raise "Please use: `./register_device UDID NAME USER [PASSWORD]`" unless ARGV.count >= 3
require 'spaceship'
Spaceship.login(ARGV, (ARGV[3] rescue nil))
Spaceship.device.create!(name: ARGV[1], udid: ARGV[0])
```

save it named `register_device`, make it executable `chmod +x register_device` and run it using

    register_device UDID NAME USER

**Comment by houweifeng** [comment]
@KrauseFx Some unexpected errors have happened.
============================================
/usr/lib/ruby/gems/2.0.0/gems/spaceship-0.0.11/lib/spaceship/client.rb:174:in `login': #<Faraday::Response:0x007f1ee39b70e0> (Spaceship::Client::InvalidUserCredentialsError)
        from /usr/lib/ruby/gems/2.0.0/gems/spaceship-0.0.11/lib/spaceship/client.rb:45:in `login'
        from /usr/lib/ruby/gems/2.0.0/gems/spaceship-0.0.11/lib/spaceship.rb:31:in `login'
        from ./register_device:4:in `<main>'

**Comment by skywinder** [comment]
+1 `ios devices:add` is broken :(

`ios devices:add "iPhone 6 Plus"=11111111 --trace`

```
ios devices:add "iPhone 6 Plus"=111111 --trace
/Users/user/.rvm/gems/ruby-2.1.5/gems/mechanize-2.5.1/lib/mechanize/http/agent.rb:304:in `fetch': 415 => Net::HTTPUnsupportedMediaType for https://developer.apple.com/services-account/XX111/account/ios/device/validateDevices.action?struts.token.name=clientToken&clientToken=XXX&register=multiple&deviceNames=&deviceNumbers= -- unhandled response (Mechanize::ResponseCodeError)
    from /Users/user/.rvm/gems/ruby-2.1.5/gems/mechanize-2.5.1/lib/mechanize.rb:407:in `get'
    from /Users/user/.rvm/gems/ruby-2.1.5@global/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/agent.rb:45:in `block in get'
    from /Users/user/.rvm/gems/ruby-2.1.5@global/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/agent.rb:44:in `times'
    from /Users/user/.rvm/gems/ruby-2.1.5@global/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/agent.rb:44:in `get'
    from /Users/user/.rvm/gems/ruby-2.1.5/gems/mechanize-2.5.1/lib/mechanize.rb:517:in `submit'
    from /Users/user/.rvm/gems/ruby-2.1.5/gems/mechanize-2.5.1/lib/mechanize/form.rb:178:in `submit'
    from /Users/user/.rvm/gems/ruby-2.1.5@global/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/agent.rb:156:in `add_devices'
    from /Users/user/.rvm/gems/ruby-2.1.5@global/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/commands/devices.rb:60:in `block (2 levels) in <top (required)>'
    from /Users/user/.rvm/gems/ruby-2.1.5/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
    from /Users/user/.rvm/gems/ruby-2.1.5/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
    from /Users/user/.rvm/gems/ruby-2.1.5/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
    from /Users/user/.rvm/gems/ruby-2.1.5/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
    from /Users/user/.rvm/gems/ruby-2.1.5/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
    from /Users/user/.rvm/gems/ruby-2.1.5/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
    from /Users/user/.rvm/gems/ruby-2.1.5/gems/commander-4.3.4/lib/commander/import.rb:8:in `block in <top (required)>'
```

**Comment by sfransen** [comment]
I used spaceship for that one call
If you look in comments in the one a reported a while ago of same problem

**Comment by skywinder** [comment]
@sfransen `spaceship` don't have CLI, so I have to write additional script for that operation. It's very nice  workaround, but it's always better to work with already implemented tools for that.

**Comment by sfransen** [comment]
I know but  to continue to work that is what I did I can send you the command to change and you you will be working too

**Comment by skywinder** [comment]
@sfransen  It would be nice!

**Comment by sfransen** [comment]
These are the steps I did and it working great

1. install spaceship
sudo gem install spaceship
2. add this line to agent.rb file at top
require "spaceship"

3. rename the existing function in devices.rb
command :'devices:add' do |c|
 to 
command :'devices:addbroken' do |c|

4. add this function to devices.rb

command :'devices:add' do |c|
	c.syntax = 'ios devices:spaceship DEVICE_NAME=DEVICE_ID [...]'
	c.summary = 'Adds a device to the Provisioning Portal using spaceship'

	c.action do |args, options|
	say_error "Missing arguments, expected DEVICE_NAME=DEVICE_ID" and abort if args.nil? or args.empty?

	args.each do |arg|
		components = arg.gsub(/"/, '').split(/\=/)
			say_ok components.first
			say_ok components.last
			Spaceship.login("account name", "password")	 # Hardcode username and password.
			Spaceship.device.create!(name: components.first, udid: components.last)

			say_warning "Invalid UDID: #{components.last}" and next unless /\h{40}/ === components.last
		end

	end
	
    say_ok "Device was Added"
end

**Comment by skywinder** [comment]
@sfransen awesome works, thanks!

@KrauseFx would you like to add such feature to https://github.com/KrauseFx/sigh?

**Comment by KrauseFx** [comment]
@skywinder what feature? Adding a new device to the Dev Portal?

**Comment by skywinder** [comment]
@KrauseFx yes

**Comment by jedi4ever** [comment]
Fwiw - we had a license to be accepted but that did not make the difference.
It might be due to the change that devices are now limited by type instead of globally 100 devices

**Comment by shannonchou** [comment]
I have the same problem for almost half a year.
