### ISSUE TITLE
feature request: I would like to automatically update all development and ad hoc profiles in an account to include every certificate and device

### ISSUE THREAD

**Issue by bradtheappguy** [nomad/cupertino#231]

**Comment by sfransen** [comment]
I have for device but not for every cert

Why would you want more then I developer cert
It a nightmare to maintain and train the developers 
Just have one development cert
 Much better
Look at my github sfransen

You can also download then all too

**Comment by bradtheappguy** [comment]
Thanks sfransen!

I just pulled for for and that gets me halfway there.  Truthfully I have considered sharing a cert across the whole development team and that may be what I end up doing.

For now, I'm going to use your fork, but if this work is desired by the maintainer, I would be interested in seeing this become a mainline feature.

**Comment by sfransen** [comment]
I will push some change tomorrow that will speed thing up if you have lots of provision profiles

Note I look for AppStore and different name to limit what I try to apply the devices to provision profiles

Note when the developer portal gets slow it off line the script breaks

I been trying to get a work around for that but it been hard

I created a website that developers and qe and managers and such can get all from and add a device to license

That way only 1 person need admin access

Control the person that have no idea what they doing

**Comment by sfransen** [comment]
I think the owner has stop looking at this code. it been a really long time now since it was changed.
