### ISSUE TITLE
Apple has changed profile page downloading - unhandled response (Mechanize::ResponseCodeError)

### ISSUE THREAD

**Issue by tommeier** [nomad/cupertino#234]
Error:

```
/opt/rubies/2.2.2/lib/ruby/gems/2.2.0/gems/mechanize-2.5.1/lib/mechanize/http/agent.rb:304:in `fetch': 404 => Net::HTTPNotFound for https://developer.apple.com/account/ios/profile/profileList.action?type=limited -- unhandled response (Mechanize::ResponseCodeError)
```

The change is quite dramatic it seems. At first it looks like a URL change:

```
        url = case type
              when :development
                'https://developer.apple.com/account/ios/profile/profileList.action?type=limited'
              when :distribution
                'https://developer.apple.com/account/ios/profile/profileList.action?type=production'
              else
                raise ArgumentError, 'Provisioning profile type must be :development or :distribution'
              end
```

became:

```
        url = case type
              when :development
                'https://developer.apple.com/account/ios/profile/limited'
              when :distribution
                'https://developer.apple.com/account/ios/profile/production'
              else
                raise ArgumentError, 'Provisioning profile type must be :development or :distribution'
              end
```

But the resulting page, is all js loaded content now:

```
<!--  -->
<!doctype html>
<html lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7, IE=9" />
    <title>Certificates, Identifiers & Profiles - Apple Developer</title>
    <meta name="description" content="Apple Developer Certificates, Identifiers & Profiles" />
    <meta name="Author" content="Apple Inc." />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="shortcut icon" href="/favicon.ico" />
    <link rel="icon" href="/favicon.ico" />
    <link rel="stylesheet" href="/account/cips/global.css" type="text/css" />
    <link rel="stylesheet" href="https://developer.apple.com/assets/core/styles/base.css" type="text/css" />
    <link rel="stylesheet" href="https://developer.apple.com/assets/core/styles/adc.css" type="text/css" />
    <link rel="stylesheet" href="https://developer.apple.com/assets/styles/jqueryui/smoothness-custom-1.8.17/jquery-ui-1.8.17.css" type="text/css" />
    <link rel="stylesheet" href="https://developer.apple.com/assets/scripts/lib/jqgrid/css/ui.jqgrid.css" type="text/css" />
    <link rel="stylesheet" href="/account/cips/cips-min.css" type="text/css" />
    <style id="css"></style>
</head>
  <body>
    <div id="app"></div>
    <script src="/account/cips/lib-min.js"></script>
    <script src="/account/cips/app-min.js"></script>
    <script src="/account/cips/account-min.js"></script>
  </body>
</html>
```

**Comment by KennethRMason** [comment]
Ran into this today, too.  All of our automated builds in our CI system are failing, due to an inability to download provisioning profiles.  We need a quick fix!!

**Comment by tommeier** [comment]
Delved a bit deeper... I don't think its a quick fix, it looks like every interaction being scraped will need updating, and the JS API reverse engineered. For example, the JSON doesn't appear to have direct specific download links.

**Comment by KennethRMason** [comment]
When I log in to the developer portal, then open Chrome's network inspector, and click "All" under "Provisioning Profiles" in the left nav, I see a different URL than the one posted in this ticket (a few parts of the URL are snipped out, like the teamID, for anonymity):
https://developer.apple.com/services-account/.../account/ios/profile/listProvisioningProfiles.action?content-type=text/x-url-arguments&accept=application/json&requestId=...&userLocale=en_US&teamId=...&includeInactiveProfiles=true&onlyCountLists=true

**Comment by KennethRMason** [comment]
Looks like some changes are starting to take place in other tools, which may expedite the fix for Cupertino: https://github.com/fastlane/spaceship/commit/ef92b7c1d7acb39b8761e48cfd1b8de6dfd5f5a7

**Comment by KennethRMason** [comment]
I cloned the repo and tried changing the URLs for listing provisioning profiles based on what I saw in the UI.  

Old URL:
https://developer.apple.com/account/ios/profile/profileList.action?type=limited'

New URL (has "services-account/QH65B2" included, which appears to be the "protocol version"):
https://developer.apple.com/services-account/QH65B2/account/ios/profile/listProvisioningProfiles.action?type=limited'

The above URL works fine in a browser, but fails when the same URL is hit via Cupertino.  It looks like this URL is requiring the presence of a session cookie, so just changing the URLs alone doesnt seem to be enough to fix it.

**Comment by KennethRMason** [comment]
@mattt / @nomad, Is this something you'll be fixing soon?

**Comment by nonemoreblack** [comment]
We're experiencing this too. Hopefully there will be a fix or workaround soon - our automation relies on cupertino to sync profiles and it's all broken right now. :-(

**Comment by sfransen** [comment]
@KennethRMason what cookie you passed I was not able to make it work when I tried

**Comment by crtlabs** [comment]
Just bumping this, woke up today with vision of nice friday, came to work and noticed that all iOS builds are red...

**Comment by atomicus** [comment]
Woke up, having end of week in mind. Came to work, and noticed all those red builds... 
Asking nicelly to at least fix download:all for the moment.

**Comment by tokyowizard** [comment]
> Asking nicelly to at least fix download:all for the moment.

+1

**Comment by danieljimenez** [comment]
Having the same issue! Does fastlane/SpaceShip have a direct replacement?

**Comment by jorgeazevedo** [comment]
@danieljimenez spaceship was patched a few hours ago, so [sigh](https://github.com/fastlane/sigh) is working. The equivalent functionality is something like

    sigh download_all  --skip_install -u EMAIL

The problem for me is the filenames are different from `cupertino`, I can't get it to pick up the password from the keychain automatically.

I wrote a basic ruby script using spaceship directly to output filenames like `cupertino`.

```ruby
#!/usr/bin/env ruby
require 'spaceship'
Spaceship.login("EMAIL")

# Find all provisioning profile objects with names including "Guardian Live" or "Guardian iPad edition"
# Write them to a file, replacing all spaces with underscores
profiles = Spaceship.provisioning_profile.all.find_all { |profile| profile.name.include? "Some basic filtering option" }
profiles.find_all do |profile|
	puts "Downloading #{profile.name}"
	File.write("#{profile.name.gsub(" ", "_")}.mobileprovision", profile.download)
end
```

**Comment by danieljimenez** [comment]
Thanks! Luckily filename isn't important to me, but scriptability is. Will look into the keychain stuff.

**Comment by sfransen** [comment]
Thanks I will try this out

**Comment by KennethRMason** [comment]
Looks like no fix is yet available, so I've figured out how to get our systems switched over to Sigh.  In case this helps anyone else:

We previously were using this Cupertino command in our CI systems to download a profile by name, on the fly during a build:
`ios profiles:download "$profileName" --team="$profileTeamName" --type=distribution --username="some@email.address" --password="..."`

The equivalent to this in Sigh is as below (note you additionally need to provide the app identifier):
`export FASTLANE_PASSWORD="..."`
`sigh -n "$profileName" -u some@email.address -l "$profileTeamName" -q downloaded.mobileprovision -a some.bundle.identifier -z --skip_install true`

**Comment by KennethRMason** [comment]
@jorgeazevedo / @danieljimenez : Note in the above script, you can specify the password in an environment variable, if that's more convenient for your CI systems than wrestling with keychain.

**Comment by swl367** [comment]
@KennethRMason thanks. I appreciate the alternative using fastlane tools. Is the team name required? I tried without it and it seems like it downloaded correctly.

**Comment by KennethRMason** [comment]
@swl367 You probably don't need the team name if you only have access to one team from the given credentials.  In our case, we have a separate org for our Enterprise profiles (AdHoc / Distribution live in a separate one).

**Comment by KennethRMason** [comment]
@swl367, heads up i amended my example above, given some further tweaking I did to the command line.

**Comment by sfransen** [comment]
Problem it doesn't work for my on my company account
It too large too many provisions profiles

Works on my personal account

**Comment by nonemoreblack** [comment]
Does fastlane/spaceship have limitations in the number of profiles it can download? Our company also has hundreds but spaceship is only finding about a third of them.

**Comment by swl367** [comment]
@sfransen @nonemoreblack is there a possibility that they aren't using the fairly new paging that the developer portal introduced?

**Comment by KennethRMason** [comment]
Maybe we've been lucky, but we haven't had any errors yet from switching to Sigh 1.4.0, and we have hundreds of profiles, too!

**Comment by sfransen** [comment]
this this command  to download all the provisions profiles
sigh download_all --force debug

 Also if you hate the Names that it create for each problem provision change this line of code. in sign

      #profile_name = "#{profile.class.pretty_type}_#{profile.app.bundle_id}.mobileprovision" # default name

      profile_name = "#{profile.name}.mobileprovision"
 in this file
/Library/Ruby/Gems/2.0.0/gems/sigh-1.4.0/lib/sigh/download_all.rb
and you will have the real names now

**Comment by nonemoreblack** [comment]
It's not a paging issue or a number of profiles issue. I just switched to a team with only 11 profiles. Cupertino used to find all of them. Spaceship and Sigh both find only 4. I guess I'm out of luck - I've resorted to manually installing our profiles on the slaves for now. Uggg...

**Comment by nonemoreblack** [comment]
Figured it out. Fastlane/Spaceship skips the "managed by xcode" profiles. I don't think we need those, so I'm switching our CI and production builds to fastlane. Just in time for the weekend.

**Comment by kentpickard** [comment]
Sigh works great for me too.  It actually simplified my build script as it handles downloading and installing provisioning profiles.  With cupertino, I had to write code in my script to effectively install the provisioning profiles so that are project which specifies "Automatic" for Ad-Hoc Distribution profile would work.  I highly recommend moving to sigh.

**Comment by sfransen** [comment]
Except you can't add new devices to existing provision profile
Profile.update!

Crashes

Sent from my iPhone5



Sent from my iPhone5
On Mar 8, 2016, at 8:06 AM, kentpickard <notifications@github.com<mailto:notifications@github.com>> wrote:


Sigh works great for me too. It actually simplified my build script as it handles downloading and installing provisioning profiles. With cupertino, I had to write code in my script to effectively install the provisioning profiles so that are project which specifies "Automatic" for Ad-Hoc Distribution profile would work. I highly recommend moving to sigh.

**Comment by jorgeazevedo** [comment]
@sfransen Can you share your code? I have a script that does that and ran fine on March 2nd.

**Comment by sfransen** [comment]
I will create a branch in my depot
Later today
Thanks

**Comment by sylvek** [comment]
hey @sfransen may you share the link of this branch?
Thks

**Comment by sharkusmarkus** [comment]
I have also switched my CI over to use sigh. I've retained the cupertino code however, just added a flag to say wether to use sigh or cupertino, with it defaulting to sigh.

**Comment by sylvek** [comment]
@sharkusmarkus the same

**Comment by sfransen** [comment]
https://github.com/sfransen/fastlane
 this i mine branch for fast lane. That will download all provision profiles we the right names and works with large account with lots of devices.
 Fast lane be default doesn't saved the provision profiles with the correct names. Sorry I do not find that acceptable.
