### ISSUE TITLE
unable to get devices list

### ISSUE THREAD

**Issue by urimagisto** [nomad/cupertino#236]
ios devices:list

getting

error: 404 => Net::HTTPNotFound for https://developer.apple.com/account/ios/device/deviceList.action -- unhandled response. Use --trace to view backtrace

it was working till few days ago, anyone aware of it?

**Comment by sfransen** [comment]
Almost everything is failing now

**Comment by urimagisto** [comment]
yes, do you know why? I didn't find any apple dev site info about it

**Comment by sfransen** [comment]
Apple change the URLs  and JSON files response 
and alot more

Spaceship

Fastlane has a fix already but not for everything as of yet
 But are working hard to fix the problem
