### ISSUE TITLE
error: Cupertino::ProvisioningPortal::UnexpectedContentError. 

### ISSUE THREAD

**Issue by hw20101101** [nomad/cupertino#238]
shikeim01deMac-mini:~ shikeim01$ ios devices:list
error: Cupertino::ProvisioningPortal::UnexpectedContentError. Use --trace to view backtrace

thank you.

**Comment by sfransen** [comment]
Apple changed all the urls and more

**Comment by DaveKap** [comment]
Would this be why I can't get Cupertino working at all now? It needs to be updated with all the URLs that have changed?

**Comment by sfransen** [comment]
More the just URLs have change

**Comment by vishweshji** [comment]
Any updates on this ?

**Comment by DaveKap** [comment]
Go grab "Sigh" here: https://github.com/fastlane/sigh Solved all my problems.

**Comment by vishweshji** [comment]
I want to automate adding new devices and generating provisioning profiles. Sigh doesn't seem to have that.
Like maintain - devices.txt
UDID1 device_name_1
UDID2 device_name_2

**Comment by sfransen** [comment]
If you check out my branch of fastlane

https://github.com/sfransen/fastlane

 you can add to device to license and then add to all provision profiles.

the syntax to do this would be

*sign download_all --force debug --verbose --username foo@yahoo.com
<foo@yahoo.com> --skip_install*

it works for me up to a point with I got too many Devices and Provision
profiles in the license

 i get timeouts

 But on any reasonable license it will be fine.
 But I have a very large License and I trying to solve my problem.
 I am also downloading the Provision profiles is the correct names not what
Spaceship default to.


if you have a problem let me know.

 so the way to install this is to do normal install

sudo gem install fastlane
sudo gem install sigh

then you will need to merge my changes to the spaceship and sigh.
 I will try and update to the latest version of the their code and then it
will be easier.

Steven Fransen

**Comment by subatomicglue** [comment]
Getting this same type of message today.
Tried two accounts and same results.
All ios commands I try give a similar result.

$ ios app_ids:list --trace
/Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/agent.rb:342:in `list_app_ids': Cupertino::ProvisioningPortal::UnexpectedContentError (Cupertino::ProvisioningPortal::UnexpectedContentError)
	from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/commands/app_ids.rb:12:in `block (3 levels) in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/helpers.rb:58:in `try'
	from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/commands/app_ids.rb:12:in `block (2 levels) in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/import.rb:5:in `block in <top (required)>'

**Comment by subatomicglue** [comment]
Just saw this added as pull request:

**Note:** Cupertino stopped working due to a recent change on the Apple Developer Portal. A maintained alternative is to use [spaceship](https://spaceship.airforce) to communicate with Apple's Developer back-end, or use any of the [fastlane tools](https://fastlane.tools), like [match](https://github.com/fastlane/match) or [sigh](https://github.com/fastlane/sigh).

**Comment by serjepatoff** [comment]
So this tool is unresistant to the portal change and no fix was done for more than a year?!! Why does it still remain public after this? Remove it if you don't want to support, it garbages already overclogged informational space. Or at least make a big red disclaimer that it is dead.

**Comment by Marslo** [comment]
Same issue also. Here details:
**```$ ios app_ids:list --trace
/Library/Ruby/Gems/2.3.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/agent.rb:342:in `list_app_ids': Cupertino::ProvisioningPortal::UnexpectedContentError (Cupertino::ProvisioningPortal::UnexpectedContentError)
	from /Library/Ruby/Gems/2.3.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/commands/app_ids.rb:12:in `block (3 levels) in <top (required)>'
	from /Library/Ruby/Gems/2.3.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/helpers.rb:58:in `try'
	from /Library/Ruby/Gems/2.3.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/commands/app_ids.rb:12:in `block (2 levels) in <top (required)>'
	from /Library/Ruby/Gems/2.3.0/gems/commander-4.4.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-4.4.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-4.4.4/lib/commander/runner.rb:446:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/commander-4.4.4/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-4.4.4/lib/commander/import.rb:5:in `block in <top (required)>'**
```
