### ISSUE TITLE
cupertino not working

### ISSUE THREAD

**Issue by ashukhobragade** [nomad/cupertino#239]
please update 

Thanks in advance

**Comment by sfransen** [comment]
Use github.com/fastlane

**Comment by ashukhobragade** [comment]
But Fastlane doesn't provide list of provisioning profile and list of certificates like Cupertino was givig

**Comment by KrauseFx** [comment]
@ashtom You can always use spaceship to have more control, including listing of certificates and provisioning profiles

**Comment by hotsjf** [comment]
@KrauseFx There is one thing missing in spaceship, adding devices to existing provision:)

**Comment by KrauseFx** [comment]
Nope, that works without problems, it's even built-in and enabled by default 👍

**Comment by hotsjf** [comment]
Hey @KrauseFx
I'm not sure if you are replying me, but I couldn't find anything in Spaceship where can do thing like this: `profiles:manage:devices:add`

If there is such thing in  Spaceship or Fastlane, please point out to me, thanks a lot for your help and great work.

**Comment by KrauseFx** [comment]
@hotsjf Yeah, you can do that: https://github.com/fastlane/fastlane/blob/master/spaceship/docs/DeveloperPortal.md
It's a Ruby library, so you'll have to use Ruby code .

Basically you can just do something like this

```ruby
Spaceship.provisioning_profile.all do |profile|
  profile.repair!
  profile.download
end
```

**Comment by hotsjf** [comment]
@KrauseFx Oh man, silly me... I read the doc many times, never took a look at the very bottom part...

Thank you so much for your great works!

**Comment by KrauseFx** [comment]
Glad it helps 👍
