### ISSUE TITLE
How to mirror Cupertino behaviour in Fastlane

### ISSUE THREAD

**Issue by sharkusmarkus** [nomad/cupertino#240]
I know this isn't an issue, but I wanted to provide some information that may help others in the same position as myself.

I had relied upon Cupertino to handle provisioning profiles in my CI setup for building iOS apps (simulator and device. In House / Enterprise, Debug, AdHoc, App Store)

As we know, Apple made changes to how the website worked, which caused Cupertino to stop functioning. The workaround suggested by many was to move to Fastlane, specifically the sigh tool.

Sigh is very powerful and useful, don't get me wrong. The repair feature is fantastic. However, I could not replicte Cupertino's operation. I simply cannot provide a profile name and download that profile. You have to provide a bundle ID as well. For the vast majority, that likely isn't a problem and it just works, but for me, that's not the case.

After asking on Faslane wether I was missing something, and if not, will they add functionality to Sigh to replicate Cupertino's behaviour, it was suggested I look at the Spaceship component of Fastlane.

It took me a fair few hours, as I've never used Ruby before, but I believe I've come up with code that will allow me to download a specific profile by name. I also added the ability to repair just that specified profile and not all of them - which is the behaviour of Sigh's repair function.

There's obviously no check as to wether you have the code signing identity / keys to actually use the profile you downloaded. But hey, if we're looking at sigh, we likely know the pitfalls of provisioning and code signing.

Below is the code I came up with. I execute it by calling the appropriate .rb file within my Execute Shell build phase of a Jenkins job.

I hope that this might prove useful to other people :)

**Code to repair a specific provisioning profile**

```
Usage:
./repair_specific_provisioning_profile.rb "myemail@email.com" "PaSSw0rd" "TMGXYQV"  "My Provisioning Profile Name"
```

```
#!/usr/bin/env ruby
# This script will use Spaceship - part of the Fastlane tools - to login to the developer portal and repair the specified provisioning profile

the_user_name = ARGV[0]
the_user_password = ARGV[1]
the_team_id = ARGV[2]
the_profile_name = ARGV[3]

require "spaceship"
begin
    puts ""
    # Login
    puts "   Logging into Developer Portal as: '#{the_user_name}'"
    puts ""
    Spaceship.login(the_user_name, the_user_password)

    # Select team
    puts "   Selecting team: '#{the_team_id}'"
    puts ""
    Spaceship.client.team_id = the_team_id

    # Find the exact profile we're looking for
    puts "   Finding profile named: '#{the_profile_name}'"
    puts ""
    my_profile = Spaceship.provisioning_profile.all.find { |p| p.name == the_profile_name }

    # Repair the profile
    puts "   Repairing profile named: '#{the_profile_name}'"
    puts ""
    my_profile.repair!
end
```

**Code to download a specific profile**

```
Usage:
./download_specific_provisioning_profile.rb "myemail@email.com" "PaSSw0rd" "TMGXYQV"  "My Provisioning Profile Name" "/path/to/profile/location"
```

```
#!/usr/bin/env ruby
# This script will use Spaceship - part of the Fastlane tools - to login to the developer portal and download the specified provisioning profile
the_user_name = ARGV[0]
the_user_password = ARGV[1]
the_team_id = ARGV[2]
the_profile_name = ARGV[3]
base_profile_path = ARGV[4]


require "spaceship"
begin
    puts ""
    # Login
    puts "   Logging into Developer Portal as: '#{the_user_name}'"
    puts ""
    Spaceship.login(the_user_name, the_user_password)

    # Select team
    puts "   Selecting team: '#{the_team_id}'"
    puts ""
    Spaceship.client.team_id = the_team_id

    # Find the exact profile we're looking for
    puts "   Finding profile named: '#{the_profile_name}'"
    puts ""
    my_profile = Spaceship.provisioning_profile.all.find { |p| p.name == the_profile_name }

    # Download the profile
    the_profile_name = the_profile_name.tr(' ', '_')
    the_profile_path = "#{base_profile_path}#{the_profile_name}.mobileprovision"
    puts "   Downloading profile named named: '#{the_profile_name}' to: '#{the_profile_path}'"
    puts ""
    File.write(the_profile_path, my_profile.download)
end
```

**Some notes:**
the_user_name = Email address of the account that has access to the Developer Portal. For repairing a profile you'd need "Admin" permissions

the_user_password = Password for the above account

the_team_id = The Team ID for the above account. You can find it by signing into the Developer Portal, the selecting Account, and then the Membership option, you will then see "Team ID" listed there.

the_profile_name = The name of the profile as specified in the development portal. If you click on a profile in the portal then it's the item specified by "Name:". _Note:_ The profile name when downloaded will have spaces replaced with underscores. This is the same behaviour as the development portal

base_profile_path = Path to where you want the profile to be downloaded to. _Note:_ Do not supply a trailing slash on the path.

**Comment by KrauseFx** [comment]
This is great, thank you so much for sharing and describing your solution. Just for future reference, this was the original discussion: https://github.com/fastlane/fastlane/issues/5262#issuecomment-230101215

Your post will be very useful for other people looking for this via Google or GitHub 👍
